language: swift
osx_image: xcode12.2 
xcode_project: TheMealAppPods.xcodeproj 
xcode_workspace: TheMealAppPods.xcworkspace
podfile: Podfile
xcode_scheme: TheMealAppPods
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro
